"""Styles package for StockMind-AI Design System."""

from frontend.styles.theme import (
    apply_terminal_theme,
    apply_terminal_chart_theme,
    get_theme_colors,
    get_semantic_signal,
    THEME_PALETTE,
    BG_PRIMARY,
    BG_SECONDARY,
    BG_TERTIARY,
    PANEL,
    PANEL_HOVER,
    BORDER,
    ACCENT_CYAN,
    ACCENT_BLUE,
    ACCENT_PURPLE,
    BULLISH,
    BULLISH_SOFT,
    BEARISH,
    BEARISH_SOFT,
    WARNING,
    NEUTRAL,
    TEXT_PRIMARY,
    TEXT_SECONDARY,
    TEXT_MUTED,
)

__all__ = [
    "apply_terminal_theme",
    "apply_terminal_chart_theme",
    "get_theme_colors",
    "get_semantic_signal",
    "THEME_PALETTE",
    "BG_PRIMARY",
    "BG_SECONDARY",
    "BG_TERTIARY",
    "PANEL",
    "PANEL_HOVER",
    "BORDER",
    "ACCENT_CYAN",
    "ACCENT_BLUE",
    "ACCENT_PURPLE",
    "BULLISH",
    "BULLISH_SOFT",
    "BEARISH",
    "BEARISH_SOFT",
    "WARNING",
    "NEUTRAL",
    "TEXT_PRIMARY",
    "TEXT_SECONDARY",
    "TEXT_MUTED",
]
